version: "3.9"

services:
  service:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=shortener
      - POSTGRES_PASSWORD=shortener
      - POSTGRES_DB=shortener
