application:
  host: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/shortener
    username: shortener
    password: shortener
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
